### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by reidjs** [reidjs/eventbike#1]
- [x] Backend: DB, model, controller, JSON views
- [x] Redux loop: ajax, actions, reducer
- [x] React components 
- [x] Styling
- [x] Smooth, bug free navigation 
- [x] Demo user

**Comment by s-pangburn** [comment]
- [ ] When I first open the page, it seems to bug out and the login modal pops up saying "Sorry, you must be logged in to perform this action". I can't actually recreate it because every time I refresh the page it doesn't happen anymore, but this is important to fix because it will impact any employer who is seeing your site for the first time (which will be most of them)

   + This is the output I get from the console, if it helps: 
![screen shot 2017-11-25 at 8 51 34 am](https://user-images.githubusercontent.com/8031316/33232606-f4152daa-d1bd-11e7-9f3d-e6df874f65d2.png)

  + None of this happens on the refreshed page.

**Comment by s-pangburn** [comment]
Additionally:

- [ ] The Eventbike logo should be just a little bigger and more prominent
- [ ] Demo user button should be the same size and length as the Get Started button
- [ ] `Create Event`'s hover effect is inconsistent with the other two buttons, make them all do the same thing (preferably the darkening effect you have on the other two)
- [ ] The input field shrinking effect when you click on it is a little too much. Just have the edges highlight.
- [ ] The edit username button needs to be a little smaller and maybe black instead of white. As it is, it looks kind of "thrown in", even though I know that's not actually true.
  + The shadow effect on hover looks a little dated by web design standards, go for something a little more subtle.
  + Would probably look nicer to have a smaller, black edit button (with white text) on the same line as the username?
- [ ] The hover effect on my username takes too long to pop up. Sometimes, I move my mouse down too quickly and the menu disappears because the animation didn't have enough time to finish. Mildly frustrating.
- [ ] Your errors should always be centered. `Invalid login credentials` and `Please fill in the username` are over to the right and look unprofessional.
- [ ] Your errors should also have a good degree of whitespace around them. They look cramped between the password field and the Log in button.
- [ ] Also, your errors don't clear if I click the Edit button to change my username.
- [ ] The eB logo at the top would probably look better the font matched the actual Eventbike logo. Check how Eventbrite does this on their website to promote a sense of coherency between the form and the logo.
- [ ] Also take a look at how things are sized relative to each other on the Eventbrite site. Try to match that more closely. Some things are too big right now (the session buttons) and others are too small (the logo, for example)

**Comment by s-pangburn** [comment]
That being said, the click-through sign in form that chooses to sign you up or sign you in based on your username is really well-done, and it should set you apart from other bootcamp grads once it's been polished up. Good work with that, and good luck this weekend!

**Comment by reidjs** [comment]
Thanks for the detailed feedback! It’s super helpful

**Comment by reidjs** [comment]
Thanks for the detailed feedback!

**Comment by s-pangburn** [comment]
Sure! It's hard to focus on little details like this when you're trying to plan out and debug the whole thing, but those tend to make all the difference. Glad it helps :)

**Comment by s-pangburn** [comment]
Remember to have errors clear when you click the icon to edit the username! Once that's done, I'll sign off on this!

**Comment by reidjs** [comment]
Fixed that issue

**Comment by s-pangburn** [comment]
Did you push to heroku?
![screen shot 2017-12-01 at 9 08 03 am](https://user-images.githubusercontent.com/8031316/33494159-2b9d7a58-d677-11e7-8437-b9bca13083e1.png)

**Comment by s-pangburn** [comment]
👌
