### ISSUE TITLE
PA Review: Registration/Tickets

### ISSUE THREAD

**Issue by reidjs** [reidjs/eventbike#7]
- [x] Users may register for an event by providing their name
- [x] Event show page updates when user confirms 
- [x] Event has a registration form where user enters their name (if logged in, this is automatic). 
- [x] Users may "one-click" register if they have an account
- [ ] ~~Guests may register if they enter their information~~
- [ ] ~~Guests may quickly sign up for an account (using a checkbox) after they input the above information~~

**Comment by reidjs** [comment]
Crossed out the last two, asks guest to sign in instead

**Comment by s-pangburn** [comment]
- [ ] Your Register button in the modal that pops up should darken just like the one on the event show page. It does this drop shadow effect that isn't as coherent with the rest of the website.
- [ ] Maybe include a few pre-registered events and bookmarks in your seed data for the guest user - would just make a better impression

Otherwise, looks good!

**Comment by reidjs** [comment]
I added a few more seeds, but what do you mean by that first comment? It opens the same modal as far as i can tell
